---
title: "graffiti_practice"
author: Sangbin Lee
- | Student number: 21107925   
date: "`r format(Sys.time(), '%X, %d %B, %Y')`"
output: html_document
---

# Original Declaration
I, [Sangbin Lee], confirm that the work presented in this assessment is my own. Where information has been derived from other sources, I confirm that this has been indicated in the work.
date: "`r format(Sys.time(), '%X, %d %B, %Y')`"

## Initial Project Overview
ddd

## Data Summary
'Graffiti.csv' file contains the 686,504 graffiti inforations gathered from 2009 to 2021. 


```{r warning=FALSE, message=FALSE}
#package call
library(tidyverse) # pipe operator and dplyr
library(fs) #
library(sf)
library(tmap)
library(janitor)
library(broom)
library(car)
library(spdep)

```

```{r}
shape <- st_read(here::here("Data", "geo_export_1880c57b-4ccd-428f-abe5-a20aa5159802.shp"))%>%
  st_transform(., crs=7131)

qtm(shape)
st_geometry(shape)
```

```{r}
graffiti <- read_csv("https://data.sfgov.org/api/views/vg6y-3pcr/rows.csv?accessType=DOWNLOAD&bom=true&format=true")
```

```{r}
graffiti2<-graffiti%>%
  separate(., Point, c("A", "B"), sep = ",")

head(graffiti2, n=5)
```

```{r}
graffiti2$A<-parse_number(graffiti2$A) ## leading $ and grouping character , ignored
graffiti2$B<-parse_number(graffiti2$B) ## leading $ and grouping character , ignored
```

```{r}
graffiti3<- graffiti2%>%
  filter(A !=	0)%>%
  filter(B != 0)%>%
  st_as_sf(., coords = c("B", "A"),
           crs = 4326)
```

```{r plot}
tmap_mode("plot")
tm_shape(shape) +
  tm_polygons(col = NA, alpha = 0.5) +
  tm_shape(graffiti4) +
  tm_dots(col = "blue")
```

```{r}
points_sf_joined1 <- shape%>%
  st_join(graffiti4)

```

```{r plot2}
tm_shape(shape_within)+
  tm_polygons(col=NA, alpha=0.5)

tmap_mode('plot')
tm_shape(shape_within)+
  tm_polygons(col=NA, alpha=0.5)+
  tm_shape(graffiti_within)+
  tm_dots(col='blue')

```

```{r}
graffiti4SP.ppp%>%
  density(., sigma=50)%>%
  plot(main = 'Graffiti Kernel Density Estimation)

```

```{r}
tm_shape(points_sf_joined) +
  tm_polygons('density',
              style='jenks',
              palette='Greys',
              midpoint=NA,
              popup.vars=c('neighborhood', 'density'),
              title='Graffiti Density')
```

```{r}


```

```{r}
```

```{r}
```

```{r}
```

```{r}
```
